title: Information Companion
author: An/Asu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the Information Companion for BPA chapters in planning their attendance at NLC in Orlando, Florida.
  Produced by An and Zhia from Eisenhower Senior High School for the convenience of future users of this Companion!
  Our personal motivations involve providing the most pleasant experience possible on every scholars' trip.

# social links
twitter_username: Antheflan
github_username:  antheflan

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
